GET http://localhost:3000/api/members

### //request를 구분하기 위해 표시
POST http://localhost:3000/api/members
Content-Type: application/json

{
    "name": "William",
    "team": "Engineering",
    "position": "Android Developer",
    "emailAddress": "zake@google.com",
    "phoneNumber": "010-xxxx-xxxx",
    "admissionDate": "2021/06/12",
    "birthday": "1995/09/27",
    "profileImage": "profile11.png"
}

###
PUT http://localhost:3000/api/members/100
Content-Type: application/json


###
DELETE http://localhost:3000/api/members/3
